# Adapted from https://github.com/PyMySQL/PyMySQL/blob/master/.travis.yml
dist: xenial
language: python
cache: pip

services:
  - docker

matrix:
  include:
    - env:
        - TOXENV=py35
        - DB=mariadb:5.5
        python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.0
      python: "3.6"
    - env:
        - TOXENV=py27
        - DB=mariadb:10.2
      python: "2.7"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.3
      python: "3.7"
    - env:
        - TOXENV=py37-dev
        - DB=mariadb:10.3
      python: "3.7-dev"
    - env:
        - TOXENV=py35
        - DB=mysql:5.5
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mysql:5.6
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mysql:5.7
      python: "3.7"
    - env:
        - TOXENV=py37
        - DB=mysql:8.0
      python: "3.7"
    - env:
        - TOXENV=py37-dev
        - DB=mysql:8.0
      python: "3.7-dev"
    - env:
        - TOXENV=py27
        - DB=mysql:8.0
      python: "2.7"

install:
  - pip install -U codecov
  - pip install -U tox-travis
  - pip install -e .

before_script:
  - bash ./.travis/initdb.sh
  - python -VV
  - rm -f ~/.my.cnf

script:
  - tox

env:
  - CODECOV_TOKEN="5fab9c13-e207-4df6-941b-f7306f35c5ef"

after_success:
  - codecov