# Adapted from https://github.com/PyMySQL/PyMySQL/blob/master/.travis.yml
dist: bionic
language: python
cache: pip

services:
  - docker

matrix:
  allow_failures:
    - env:
        - TOXENV=py27
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
      - TOXENV=pypy
      - DB=mariadb:5.5
      - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
      - TOXENV=pypy3
      - DB=mariadb:5.5
      - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=pypy3
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "pypy3"
  include:
    - env:
        - TOXENV=py27
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mariadb:5.5
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.0
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.1
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.2
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.3
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.4
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mariadb:10.5
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mysql:5.5
        - LEGACY_DB=1
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mysql:5.5
        - LEGACY_DB=1
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mysql:5.5
        - LEGACY_DB=1
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mysql:5.5
        - LEGACY_DB=1
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mysql:5.5
        - LEGACY_DB=1
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mysql:5.6
        - LEGACY_DB=1
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mysql:5.7
        - LEGACY_DB=0
      python: "pypy3"
    - env:
        - TOXENV=py27
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "2.7"
    - env:
        - TOXENV=py35
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "3.5"
    - env:
        - TOXENV=py36
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "3.6"
    - env:
        - TOXENV=py37
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "3.7"
    - env:
        - TOXENV=py38
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "3.8"
    - env:
        - TOXENV=py39-dev
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "3.9-dev"
    - env:
        - TOXENV=pypy
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "pypy"
      dist: xenial
    - env:
        - TOXENV=pypy3
        - DB=mysql:8.0
        - LEGACY_DB=0
      python: "pypy3"

install:
  - pip install -U codecov
  - pip install -U tox-travis
  - pip install -e .

before_script:
  - bash ./.travis/initdb.sh
  - python -VV
  - mysql -V
  - rm -f ~/.my.cnf

script:
  - tox

env:
  - CODECOV_TOKEN="5fab9c13-e207-4df6-941b-f7306f35c5ef"

after_success:
  - codecov